# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Visaal's Blogs
email: visaalpathak@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I always wanted to write blogs about what I learn and make it easier for others to learn similar things. Being a Data Science enthusiast, I want to make it easier for beginners like me to learn things that are essential to be a good data scientist. I will update blogs with my own journey of learning things.
twitter_username: MVisaal
github_username: VisaalPathak
minimal_mistakes_skin: default
search: true
repository: "VisaalPathak/VisaalPathak.github.io"
issues_repo: "VisaalPathak/VisaalPathak.github.io"

# Build settings
markdown: kramdown
repository: VisaalPathak/VisaalPathak.github.io
remote_theme: mmistakes/minimal-mistakes
logo: "./assets/pp.jpg"
# theme: minimal-mistakes-jekyll
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Visaal Pathak"
  avatar : "/assets/images/bio-photo.jpeg"
  bio    : "Let's Learn Together"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://visaalpathak.github.io/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MVisaal"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/VisaalPathak"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/bishal-pathak-5900a4201/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MVisaal"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/VisaalPathak"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/bishal-pathak-5900a4201/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

comments:
  provider: "utterances"
  utterances:
    theme:  "github-light" #"github-dark"
    issue_term: 'pathname'

tag_archive:
  type: liquid
  path: /tags/
